#pragma checksum "..\..\AdminWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B6E58F52D6515BE32445965CE65F46FB73562491"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PecoDropDesktopApp {
    
    
    /// <summary>
    /// AdminWindow
    /// </summary>
    public partial class AdminWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 54 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtHeaderSqlStatus;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtHeaderApiStatus;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl AdminTabs;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PointsGrid;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid TransactionsGrid;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ComparisonSyncBadgeBorder;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ComparisonSyncBadgeText;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtLocalTotalItems;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCentralTotalItems;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtLocalTotalPoints;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCentralTotalPoints;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridVariantComparison;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtComparisonSummary;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSyncTargetUrl;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSyncStatus;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdCurrentAdmin;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdNewAdmin;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdConfirmAdmin;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridLocalPointSettings;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgMachineId;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgCentralApiUrl;
        
        #line default
        #line hidden
        
        
        #line 335 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgLocation;
        
        #line default
        #line hidden
        
        
        #line 347 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgLatitude;
        
        #line default
        #line hidden
        
        
        #line 351 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgLongitude;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgConnectionString;
        
        #line default
        #line hidden
        
        
        #line 381 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgArduinoPort;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgArduinoBaud;
        
        #line default
        #line hidden
        
        
        #line 396 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgCameraPort;
        
        #line default
        #line hidden
        
        
        #line 400 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgCameraBaud;
        
        #line default
        #line hidden
        
        
        #line 418 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgAdsFolder;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgInstructionsFolder;
        
        #line default
        #line hidden
        
        
        #line 433 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgModelPath;
        
        #line default
        #line hidden
        
        
        #line 437 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CfgCaptureDir;
        
        #line default
        #line hidden
        
        
        #line 465 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtServerUrl;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtConnStatus;
        
        #line default
        #line hidden
        
        
        #line 489 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtMachineId;
        
        #line default
        #line hidden
        
        
        #line 493 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtUserId;
        
        #line default
        #line hidden
        
        
        #line 504 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbMaterial;
        
        #line default
        #line hidden
        
        
        #line 515 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbSize;
        
        #line default
        #line hidden
        
        
        #line 530 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtItemCount;
        
        #line default
        #line hidden
        
        
        #line 534 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtWeightKg;
        
        #line default
        #line hidden
        
        
        #line 576 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtConsoleLog;
        
        #line default
        #line hidden
        
        
        #line 651 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridAdVideos;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPreviewVideoTitle;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement AdminAdPlayer;
        
        #line default
        #line hidden
        
        
        #line 702 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPlayerPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 714 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPlayPausePreview;
        
        #line default
        #line hidden
        
        
        #line 715 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStopPreview;
        
        #line default
        #line hidden
        
        
        #line 716 "..\..\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPlayerTime;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PecoDropDesktopApp;component/adminwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\AdminWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtHeaderSqlStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtHeaderApiStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            
            #line 68 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenSimulator_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 74 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Refresh_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 79 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Save_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.AdminTabs = ((System.Windows.Controls.TabControl)(target));
            return;
            case 7:
            this.PointsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 8:
            this.TransactionsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 9:
            this.ComparisonSyncBadgeBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.ComparisonSyncBadgeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            
            #line 133 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RefreshComparisonData_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.TxtLocalTotalItems = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.TxtCentralTotalItems = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.TxtLocalTotalPoints = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.TxtCentralTotalPoints = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.GridVariantComparison = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 17:
            this.TxtComparisonSummary = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            
            #line 196 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SyncLocalData_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TxtSyncTargetUrl = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            
            #line 220 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SyncLocalData_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.TxtSyncStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.PwdCurrentAdmin = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 23:
            this.PwdNewAdmin = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 24:
            this.PwdConfirmAdmin = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 25:
            
            #line 244 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ChangePassword_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 261 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SyncPointSettings_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.GridLocalPointSettings = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 28:
            
            #line 310 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReloadConfig_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 311 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveConfig_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.CfgMachineId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.CfgCentralApiUrl = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.CfgLocation = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.CfgLatitude = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.CfgLongitude = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            
            #line 353 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AutoDetectLocation_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.CfgConnectionString = ((System.Windows.Controls.TextBox)(target));
            return;
            case 37:
            this.CfgArduinoPort = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.CfgArduinoBaud = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.CfgCameraPort = ((System.Windows.Controls.TextBox)(target));
            return;
            case 40:
            this.CfgCameraBaud = ((System.Windows.Controls.TextBox)(target));
            return;
            case 41:
            
            #line 403 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReinitializeArduino_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.CfgAdsFolder = ((System.Windows.Controls.TextBox)(target));
            return;
            case 43:
            this.CfgInstructionsFolder = ((System.Windows.Controls.TextBox)(target));
            return;
            case 44:
            this.CfgModelPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 45:
            this.CfgCaptureDir = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.TxtServerUrl = ((System.Windows.Controls.TextBox)(target));
            return;
            case 47:
            
            #line 471 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TestConnection_Click);
            
            #line default
            #line hidden
            return;
            case 48:
            this.TxtConnStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 49:
            this.TxtMachineId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 50:
            this.TxtUserId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.CmbMaterial = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 52:
            this.CmbSize = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 53:
            this.TxtItemCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 54:
            this.TxtWeightKg = ((System.Windows.Controls.TextBox)(target));
            return;
            case 55:
            
            #line 538 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SimulateInsert_Click);
            
            #line default
            #line hidden
            return;
            case 56:
            
            #line 551 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SendHeartbeat_Click);
            
            #line default
            #line hidden
            return;
            case 57:
            
            #line 552 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.VerifyQr_Click);
            
            #line default
            #line hidden
            return;
            case 58:
            this.TxtConsoleLog = ((System.Windows.Controls.TextBox)(target));
            return;
            case 59:
            
            #line 591 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearConsole_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            
            #line 622 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BrowseAddAdVideo_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            
            #line 623 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenAdsFolder_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            
            #line 624 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RefreshAdsList_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            
            #line 625 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ApplyPlayAds_Click);
            
            #line default
            #line hidden
            return;
            case 64:
            this.GridAdVideos = ((System.Windows.Controls.DataGrid)(target));
            
            #line 662 "..\..\AdminWindow.xaml"
            this.GridAdVideos.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GridAdVideos_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 65:
            
            #line 673 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PreviewSelectedAd_Click);
            
            #line default
            #line hidden
            return;
            case 66:
            
            #line 674 "..\..\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteSelectedAd_Click);
            
            #line default
            #line hidden
            return;
            case 67:
            this.TxtPreviewVideoTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 68:
            this.AdminAdPlayer = ((System.Windows.Controls.MediaElement)(target));
            
            #line 700 "..\..\AdminWindow.xaml"
            this.AdminAdPlayer.MediaEnded += new System.Windows.RoutedEventHandler(this.AdminAdPlayer_MediaEnded);
            
            #line default
            #line hidden
            
            #line 701 "..\..\AdminWindow.xaml"
            this.AdminAdPlayer.MediaFailed += new System.EventHandler<System.Windows.ExceptionRoutedEventArgs>(this.AdminAdPlayer_MediaFailed);
            
            #line default
            #line hidden
            return;
            case 69:
            this.TxtPlayerPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 70:
            this.BtnPlayPausePreview = ((System.Windows.Controls.Button)(target));
            
            #line 714 "..\..\AdminWindow.xaml"
            this.BtnPlayPausePreview.Click += new System.Windows.RoutedEventHandler(this.PlayPausePreview_Click);
            
            #line default
            #line hidden
            return;
            case 71:
            this.BtnStopPreview = ((System.Windows.Controls.Button)(target));
            
            #line 715 "..\..\AdminWindow.xaml"
            this.BtnStopPreview.Click += new System.Windows.RoutedEventHandler(this.StopPreview_Click);
            
            #line default
            #line hidden
            return;
            case 72:
            this.TxtPlayerTime = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

