#pragma checksum "..\..\LandscapeWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BCA431A713F372ECD09935FF4E976CC3B992D97D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PecoDropDesktopApp {
    
    
    /// <summary>
    /// LandscapeWindow
    /// </summary>
    public partial class LandscapeWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 110 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LiveBadgeBorder;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveBadgeText;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RvmNameChipBorder;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveDateText;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveTimeText;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderDotText;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CommandCenterRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AdHeaderRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BottleInfoText;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse StatusDot;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ConnectionText;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse DbDot;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DbStatusText;
        
        #line default
        #line hidden
        
        
        #line 180 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse ApiDot;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ApiStatusText;
        
        #line default
        #line hidden
        
        
        #line 184 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MachineStateText;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HardwareErrorBanner;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HardwareErrorText;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border UserGreetingBanner;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GreetingUserNameText;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GreetingPointsBalanceText;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement InstructionPlayer;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid InstructionPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StartQrCard;
        
        #line default
        #line hidden
        
        
        #line 286 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image StartQrImage;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TotalPointsText;
        
        #line default
        #line hidden
        
        
        #line 372 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 373 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 374 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 379 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 400 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 405 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 424 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 425 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 426 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 431 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 450 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RejectedCountText;
        
        #line default
        #line hidden
        
        
        #line 456 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RejectedTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Co2SavedText;
        
        #line default
        #line hidden
        
        
        #line 469 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock WaterSavedText;
        
        #line default
        #line hidden
        
        
        #line 470 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TotalItemsText;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl LeaderboardList;
        
        #line default
        #line hidden
        
        
        #line 675 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerNameText;
        
        #line default
        #line hidden
        
        
        #line 676 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerTimeText;
        
        #line default
        #line hidden
        
        
        #line 678 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerActivityText;
        
        #line default
        #line hidden
        
        
        #line 683 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerPointsText;
        
        #line default
        #line hidden
        
        
        #line 717 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid;
        
        #line default
        #line hidden
        
        
        #line 718 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AdPanel;
        
        #line default
        #line hidden
        
        
        #line 719 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement AdvertisementPlayer;
        
        #line default
        #line hidden
        
        
        #line 724 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TelemetryPanel;
        
        #line default
        #line hidden
        
        
        #line 730 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TelemetryScroll;
        
        #line default
        #line hidden
        
        
        #line 731 "..\..\LandscapeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl TelemetryList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PecoDropDesktopApp;component/landscapewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\LandscapeWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 6 "..\..\LandscapeWindow.xaml"
            ((PecoDropDesktopApp.LandscapeWindow)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Window_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LiveBadgeBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.LiveBadgeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.RvmNameChipBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.HeaderRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.LiveDateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.LiveTimeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.HeaderDotText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.CommandCenterRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.AdHeaderRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.BottleInfoText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.StatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 14:
            this.ConnectionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.DbDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 16:
            this.DbStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.ApiDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 18:
            this.ApiStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.MachineStateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            
            #line 188 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DemoTestingButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.HardwareErrorBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 22:
            this.HardwareErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            
            #line 216 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DemoTestingButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 225 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RetryHardwareConnection_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.UserGreetingBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 26:
            this.GreetingUserNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.GreetingPointsBalanceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            
            #line 251 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.InstructionPlayer = ((System.Windows.Controls.MediaElement)(target));
            
            #line 253 "..\..\LandscapeWindow.xaml"
            this.InstructionPlayer.MediaEnded += new System.Windows.RoutedEventHandler(this.InstructionPlayer_MediaEnded);
            
            #line default
            #line hidden
            
            #line 253 "..\..\LandscapeWindow.xaml"
            this.InstructionPlayer.MediaFailed += new System.EventHandler<System.Windows.ExceptionRoutedEventArgs>(this.InstructionPlayer_MediaFailed);
            
            #line default
            #line hidden
            return;
            case 30:
            this.InstructionPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            
            #line 255 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.StartQrCard = ((System.Windows.Controls.Border)(target));
            
            #line 280 "..\..\LandscapeWindow.xaml"
            this.StartQrCard.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 33:
            this.StartQrImage = ((System.Windows.Controls.Image)(target));
            return;
            case 34:
            this.TotalPointsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            
            #line 336 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ViewRewardsButton_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.PlasticSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.PlasticMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.PlasticLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.PlasticTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.CanSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.CanMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.CanLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.CanTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 44:
            this.TetraPakSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.TetraPakMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 46:
            this.TetraPakLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 47:
            this.TetraPakTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.RejectedCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 49:
            this.RejectedTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.Co2SavedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.WaterSavedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.TotalItemsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 53:
            this.LeaderboardList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 54:
            this.LastRecyclerNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 55:
            this.LastRecyclerTimeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 56:
            this.LastRecyclerActivityText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 57:
            this.LastRecyclerPointsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 58:
            
            #line 703 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            
            #line 705 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StopButton_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            
            #line 707 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResetHardwareButton_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            
            #line 709 "..\..\LandscapeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CalibrateHardwareButton_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.BottomGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 63:
            this.AdPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 64:
            this.AdvertisementPlayer = ((System.Windows.Controls.MediaElement)(target));
            
            #line 719 "..\..\LandscapeWindow.xaml"
            this.AdvertisementPlayer.MediaEnded += new System.Windows.RoutedEventHandler(this.AdvertisementPlayer_MediaEnded);
            
            #line default
            #line hidden
            return;
            case 65:
            this.TelemetryPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 66:
            this.TelemetryScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 67:
            this.TelemetryList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

