#pragma checksum "..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3F6DC1803FDD341F395C39F05A9081774F46ABC3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace PecoDropDesktopApp {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 129 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LiveBadgeBorder;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveBadgeText;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RvmNameChipBorder;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveDateText;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LiveTimeText;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MachineStateText;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse StatusDot;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ConnectionText;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse DbDot;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DbStatusText;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse ApiDot;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ApiStatusText;
        
        #line default
        #line hidden
        
        
        #line 234 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HardwareErrorBanner;
        
        #line default
        #line hidden
        
        
        #line 246 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HardwareErrorText;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border UserGreetingBanner;
        
        #line default
        #line hidden
        
        
        #line 276 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GreetingUserNameText;
        
        #line default
        #line hidden
        
        
        #line 278 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GreetingPointsBalanceText;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement InstructionPlayer;
        
        #line default
        #line hidden
        
        
        #line 306 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid InstructionPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StartQrCard;
        
        #line default
        #line hidden
        
        
        #line 340 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image StartQrImage;
        
        #line default
        #line hidden
        
        
        #line 390 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TotalPointsText;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ViewRewardsButton;
        
        #line default
        #line hidden
        
        
        #line 430 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 436 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 442 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 449 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlasticTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 484 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 491 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CanTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 514 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakSmallCountText;
        
        #line default
        #line hidden
        
        
        #line 520 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakMediumCountText;
        
        #line default
        #line hidden
        
        
        #line 526 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakLargeCountText;
        
        #line default
        #line hidden
        
        
        #line 533 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TetraPakTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 553 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RejectedCountText;
        
        #line default
        #line hidden
        
        
        #line 559 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RejectedTotalCountText;
        
        #line default
        #line hidden
        
        
        #line 733 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl LeaderboardList;
        
        #line default
        #line hidden
        
        
        #line 795 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FlashingLiveBadge;
        
        #line default
        #line hidden
        
        
        #line 819 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerNameText;
        
        #line default
        #line hidden
        
        
        #line 820 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerTimeText;
        
        #line default
        #line hidden
        
        
        #line 822 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerActivityText;
        
        #line default
        #line hidden
        
        
        #line 827 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LastRecyclerPointsText;
        
        #line default
        #line hidden
        
        
        #line 838 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Co2SavedText;
        
        #line default
        #line hidden
        
        
        #line 839 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock WaterSavedText;
        
        #line default
        #line hidden
        
        
        #line 840 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TotalItemsText;
        
        #line default
        #line hidden
        
        
        #line 845 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderDotText;
        
        #line default
        #line hidden
        
        
        #line 846 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CommandCenterRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 847 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AdHeaderRvmNameText;
        
        #line default
        #line hidden
        
        
        #line 848 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 849 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BottleInfoText;
        
        #line default
        #line hidden
        
        
        #line 880 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomGrid;
        
        #line default
        #line hidden
        
        
        #line 887 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AdPanel;
        
        #line default
        #line hidden
        
        
        #line 896 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement AdvertisementPlayer;
        
        #line default
        #line hidden
        
        
        #line 947 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TelemetryPanel;
        
        #line default
        #line hidden
        
        
        #line 956 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TelemetryScroll;
        
        #line default
        #line hidden
        
        
        #line 957 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl TelemetryList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/PecoDropDesktopApp;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 6 "..\..\MainWindow.xaml"
            ((PecoDropDesktopApp.MainWindow)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Window_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LiveBadgeBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.LiveBadgeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.RvmNameChipBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.HeaderRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.LiveDateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.LiveTimeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.MachineStateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.StatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 10:
            this.ConnectionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.DbDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 12:
            this.DbStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.ApiDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 14:
            this.ApiStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            
            #line 219 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DemoTestingButton_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.HardwareErrorBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.HardwareErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            
            #line 249 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DemoTestingButton_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 258 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RetryHardwareConnection_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.UserGreetingBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 21:
            this.GreetingUserNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.GreetingPointsBalanceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            
            #line 300 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.InstructionPlayer = ((System.Windows.Controls.MediaElement)(target));
            
            #line 303 "..\..\MainWindow.xaml"
            this.InstructionPlayer.MediaEnded += new System.Windows.RoutedEventHandler(this.InstructionPlayer_MediaEnded);
            
            #line default
            #line hidden
            
            #line 303 "..\..\MainWindow.xaml"
            this.InstructionPlayer.MediaFailed += new System.EventHandler<System.Windows.ExceptionRoutedEventArgs>(this.InstructionPlayer_MediaFailed);
            
            #line default
            #line hidden
            return;
            case 25:
            this.InstructionPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            
            #line 307 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.StartQrCard = ((System.Windows.Controls.Border)(target));
            
            #line 334 "..\..\MainWindow.xaml"
            this.StartQrCard.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.StartQrImage = ((System.Windows.Controls.Image)(target));
            return;
            case 29:
            this.TotalPointsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.ViewRewardsButton = ((System.Windows.Controls.Button)(target));
            
            #line 398 "..\..\MainWindow.xaml"
            this.ViewRewardsButton.Click += new System.Windows.RoutedEventHandler(this.ViewRewardsButton_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.PlasticSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.PlasticMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.PlasticLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.PlasticTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.CanSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.CanMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.CanLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.CanTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.TetraPakSmallCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.TetraPakMediumCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.TetraPakLargeCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.TetraPakTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.RejectedCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 44:
            this.RejectedTotalCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.LeaderboardList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 46:
            this.FlashingLiveBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 47:
            this.LastRecyclerNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.LastRecyclerTimeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 49:
            this.LastRecyclerActivityText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.LastRecyclerPointsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.Co2SavedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.WaterSavedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 53:
            this.TotalItemsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 54:
            this.HeaderDotText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 55:
            this.CommandCenterRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 56:
            this.AdHeaderRvmNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 57:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 58:
            this.BottleInfoText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 59:
            
            #line 863 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            
            #line 866 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StopButton_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            
            #line 869 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResetHardwareButton_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            
            #line 872 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CalibrateHardwareButton_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            this.BottomGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 64:
            this.AdPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 65:
            this.AdvertisementPlayer = ((System.Windows.Controls.MediaElement)(target));
            
            #line 896 "..\..\MainWindow.xaml"
            this.AdvertisementPlayer.MediaEnded += new System.Windows.RoutedEventHandler(this.AdvertisementPlayer_MediaEnded);
            
            #line default
            #line hidden
            return;
            case 66:
            this.TelemetryPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 67:
            this.TelemetryScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 68:
            this.TelemetryList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

