//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/dancingcan.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/dancingplastic.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/dancingtetra.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/dancingxn.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("ads/advertisements/ad_1789147503725_peco_b.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("ads/instructions/ad_1787936050451_instructinal.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("ads/instructions/instructinal.mp4")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("ads/put_video_here.txt")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("config.txt")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("config.example.txt")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("fonts/jameel%20noori%20nastaleeq.ttf")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("fonts/notonastaliqurdu-bold.ttf")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("fonts/notonastaliqurdu-regular.ttf")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/avatars/avatar1.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/avatars/avatar2.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/avatars/avatar3.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/avatars/avatar4.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/avatars/avatar5.png")]


